Default: &defaults
  database: wellmet.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: wellmet_test.sqlite3
  <<: *defaults

Staging:
  database: wellmet_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: wellmet_production.sqlite3
  poolsize: 100
  <<: *defaults
