Default: &defaults
  database: rumble.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: rumble_test.sqlite3
  <<: *defaults

Staging:
  database: rumble_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: rumble_production.sqlite3
  poolsize: 100
  <<: *defaults
