Default: &defaults
  database: authme.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: authme_test.sqlite3
  <<: *defaults

Staging:
  database: authme_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: authme_production.sqlite3
  poolsize: 100
  <<: *defaults
